// Generated by CodiumAI

import { ActionStructureParams, generateActionStructure } from "./_action-structure";

describe("generateActionStructure", () => {
  // Generates action structure with valid parameters and device ids
  it("should generate action structure with valid parameters and device ids", () => {
    // Arrange
    const structure: ActionStructureParams = {
      org_id: "org123",
      site_id: "site123",
      equipment_id: "equip123",
      send_to: ["user1", "user2"],
      triggers: [
        {
          trigger_value: 10,
          variable: "temperature",
          condition: ">",
          trigger_id: "trigger1",
          isActive: true,
          isRecurring: false,
          deviceIdList: ["device1", "device2"],
        },
      ],
      script: "123",
    };

    // Act
    const result = generateActionStructure(structure);

    // Assert
    expect(result).toHaveLength(1);
    expect(result[0].active).toBe(true);
    expect(result[0].name).toBe("Application alert trigger DEVICE");
    expect(result[0].tags).toHaveLength(8);
    expect(result[0].tags[0]).toEqual({ key: "group_id", value: "N/A" });
    expect(result[0].tags[1]).toEqual({ key: "organization_id", value: "org123" });
    expect(result[0].tags[2]).toEqual({ key: "site_id", value: "site123" });
    expect(result[0].tags[3]).toEqual({ key: "trigger_id", value: "trigger1" });
    expect(result[0].tags[4]).toEqual({ key: "variable", value: "temperature" });
    expect(result[0].tags[5]).toEqual({ key: "equipment_id", value: "equip123" });
    expect(result[0].tags[6]).toEqual({ key: "device", value: "device1" });
    expect(result[0].tags[7]).toEqual({ key: "device", value: "device2" });
    expect(result[0].type).toBe("condition");
    expect(result[0].trigger).toHaveLength(4);
    expect(result[0].trigger[0]).toEqual({
      is: ">",
      value: "10",
      value_type: "number",
      variable: "temperature",
      device: "device1",
      second_value: undefined,
    });
    expect(result[0].trigger[1]).toEqual({
      is: "<",
      unlock: true,
      value: "10",
      value_type: "number",
      variable: "temperature",
      device: "device1",
      second_value: "",
    });
    expect(result[0].action).toEqual({
      type: "script",
      script: ["123"],
    });
  });

  // Generates action structure with valid parameters and empty device ids
  it("should generate action structure with valid parameters for boolean", () => {
    // Arrange
    const structure: ActionStructureParams = {
      org_id: "org123",
      site_id: "site123",
      equipment_id: "equip123",
      send_to: ["user1", "user2"],
      triggers: [
        {
          trigger_value: true,
          variable: "door_status",
          condition: "=",
          trigger_id: "trigger1",
          isActive: true,
          isRecurring: false,
          deviceIdList: ["123"],
        },
      ],
      script: "123",
    };

    // Act
    const result = generateActionStructure(structure);

    // Assert
    expect(result[0].trigger).toHaveLength(2);
    expect(result[0].trigger[0].is).toEqual("=");
    expect(result[0].trigger[0].value).toEqual("true");
    expect(result[0].trigger[1].is).toEqual("=");
    expect(result[0].trigger[1].value).toEqual("false");
  });

  // Generates action structure with missing trigger variable
  it("should generate action structure with missing trigger variable", () => {
    // Arrange
    const structure: any = {
      org_id: "org123",
      site_id: "site123",
      equipment_id: "equip123",
      send_to: ["user1", "user2"],
      triggers: [
        {
          trigger_value: 10,
          condition: ">",
          trigger_id: "trigger1",
          isActive: true,
          isRecurring: false,
          deviceIdList: ["device1", "device2"],
        },
      ],
      script: "123",
    };

    const spy = jest.spyOn(console, "error").mockImplementation(() => {});
    // Act
    const result = generateActionStructure(structure);
    // Assert
    expect(result).toHaveLength(0);
    expect(generateActionStructure).toThrow("Cannot read properties of undefined (reading 'triggers')");

    spy.mockRestore();
  });

  // Generates action structure with missing trigger condition
  it("should generate action structure with missing trigger condition", () => {
    // Arrange
    const structure: any = {
      org_id: "org123",
      site_id: "site123",
      equipment_id: "equip123",
      send_to: ["user1", "user2"],
      triggers: [
        {
          trigger_value: 10,
          variable: "temperature",
          trigger_id: "trigger1",
          isActive: true,
          isRecurring: false,
          deviceIdList: ["device1", "device2"],
        },
      ],
      script: "123",
    };

    const spy = jest.spyOn(console, "error").mockImplementation(() => {});
    // Act
    const result = generateActionStructure(structure);
    // Assert
    expect(result).toHaveLength(0);
    expect(generateActionStructure).toThrow("Cannot read properties of undefined (reading 'triggers')");

    spy.mockRestore();
  });
});
